# setup JM Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager-svc-2-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-svc-2-0
      component: jobmanager-svc-2-0
  template:
    metadata:
      labels:
        app: flink-svc-2-0
        component: jobmanager-svc-2-0
    spec:
      containers:
        - name: jobmanager
          image: repo/image-tag
          args: [ "jobmanager" ]
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob-server
            - containerPort: 8081
              name: webui
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
          securityContext:
            runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      imagePullSecrets:
        - name: flink-k8s-pull-secret-pub
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config-2.0-svc
            items:
              - key: config.yaml
                path: config.yaml
              - key: log4j-console.properties
                path: log4j-console.properties
