apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager-svc-2-0
spec:
  replicas: 8
  selector:
    matchLabels:
      app: flink-svc-2-0
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink-svc-2-0
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: repo/image-tag
          args: [ "taskmanager" ]
          resources:
            requests:
              cpu: 1
              memory: 20Gi
              ephemeral-storage: "80Gi"
            limits:
              cpu: 1
              memory: 20Gi
              ephemeral-storage: "80Gi"
          ports:
            - containerPort: 6122
              name: rpc
          livenessProbe:
            tcpSocket:
              port: 6122
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf/
          securityContext:
            runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      imagePullSecrets:
        - name: flink-k8s-pull-secret-pub
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config-2.0-svc
            items:
              - key: config.yaml
                path: config.yaml
              - key: log4j-console.properties
                path: log4j-console.properties
