apiVersion: v1
kind: Service
metadata:
  name: flink-svc-compactor
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink-svc-compactor
    component: jobmanager-svc-compactor